import { CommandInteraction, SlashCommandBuilder, EmbedBuilder } from 'discord.js';
import type { Command } from './index.js';
import fetch from 'node-fetch';

// Array of dramatic introductions
const intros = [
	"Behold! A profound revelation from the depths of artificial enlightenment!",
	"I present to you: the ultimate truth, carefully crafted by a random number generator!",
	"Gaze upon this, a quote so wise, only a machine could conjure it!",
	"Prepare yourself for a life-changing insight... generated by a toaster!",
	"I bring you words of wisdom, forged in the fires of the algorithmic abyss!",
	"Brace yourself: The AI has spoken, and it’s deeply... questionable.",
	"Witness the accidental brilliance of a machine's attempt at inspiration!",
];

export default {
	data: new SlashCommandBuilder()
		.setName('wisdom')
		.setDescription('Beg the almighty AI for wisdom.')
		.toJSON(),

	async execute(interaction: CommandInteraction): Promise<void> {
		try {
			// Fetch Inspirobot-generated quote image
			const response = await fetch('http://inspirobot.me/api?generate=true');
			const quoteImageUrl = await response.text();

			// Select a random introduction
			const intro = intros[Math.floor(Math.random() * intros.length)];

			// Create an embed with the quote
			const embed = new EmbedBuilder()
				.setColor(0x00DEAD)
				.setDescription(`**${intro}**`)
				.setImage(quoteImageUrl);

			// Send the embed
			await interaction.reply({ embeds: [embed] });
		} catch (error) {
			console.error('Error fetching Inspirobot quote:', error);
			await interaction.reply({ content: '❌ Failed to retrieve a quote.', ephemeral: true });
		}
	},
} satisfies Command;
